server:
  port: ${PORT:8081}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwks-uri: ${OAUTH2_JWKS_URI}
          issuer-uri: ${OAUTH2_ISSUER_URI}

  flyway:
    baseline-on-migrate: false
    out-of-order: false
    clean-disabled: true

  kafka:
    security:
      protocol: SASL_SSL
    properties:
      sasl.mechanism: SCRAM-SHA-256
      sasl.jaas.config: >
        org.apache.kafka.common.security.scram.ScramLoginModule required
        username="${KAFKA_USERNAME}"
        password="${KAFKA_PASSWORD}";
    ssl:
      trust-store-location: ${KAFKA_SSL_TRUSTSTORE_LOCATION}
      trust-store-password: ${KAFKA_SSL_TRUSTSTORE_PASSWORD}
      trust-store-type: JKS

app:
  eventos:
    kafka:
      enabled: ${EVENTOS_KAFKA_ENABLED:true}

logging:
  level:
    com.mekylei.transactionprocessing: INFO    # Apenas informações importantes
    org.springframework.web: WARN              # Só alertas e erros
    org.hibernate: WARN                        # Silencia logs do Hibernate

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false