server:
  port: ${PORT:8081}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

logging:
  level:
    com.mekylei.transactionprocessing: INFO    # Apenas informações importantes
    org.springframework.web: WARN              # Só alertas e erros
    org.hibernate: WARN                        # Silencia logs do Hibernate

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false