server:
  port: 8080

spring:
  application:
    name: transaction-processing-api
  output:
    ansi:
      enabled: always

  security:
    oauth2:
      resourceserver:
        jwt:
          jwks-uri: ${OAUTH2_JWKS_URI}
          issuer-uri: ${OAUTH2_ISSUER_URI}

  flyway:
    enabled: true
    locations: classpath:db/migration

app:
  rate-limit:
    requests-per-minute: ${RATE_LIMIT_REQUISICOES_POR_MINUTO:60}
  criptografia:
    chave: ${APP_CRIPTOGRAFIA_CHAVE}

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr([%thread]){cyan} %clr([%X{idCorrelacao:-sem-correlacao}]){magenta} %clr(%-5level) %clr(%logger{36}){green} %clr(-){faint} %msg%n"